import 'dart:async';

import 'package:flutter/material.dart';

/// This class is generated by the flappy_translator package
/// Please do not change anything manually in this file, instead re-generate it when changes are available
class I18n {
  String get title => _getText("title");

  String get description => _getText("description");

  String get send => _getText("send");

  static Map<String, String> _localizedValues;

  static Map<String, String> _enValues = {
    "title": "Welcome",
    "description": "This is the main page in this application",
    "send": "Submit",
  };

  static Map<String, String> _idValues = {
    "title": "Selamat Datang",
    "description": "Ini merupakan halaman utama dalam aplikasi ini",
    "send": "Kirim",
  };

  static Map<String, String> _zhValues = {
    "title": "欢迎",
    "description": "这是该应用程序的主页",
    "send": "提交",
  };

  static Map<String, Map<String, String>> _allValues = {
    "en": _enValues,
    "id": _idValues,
    "zh": _zhValues,
  };

  I18n(Locale locale) {
    this._locale = locale;
    _localizedValues = null;
  }

  Locale _locale;

  static I18n of(BuildContext context) {
    return Localizations.of<I18n>(context, I18n);
  }

  String _getText(String key) {
    return _localizedValues[key] ?? '** $key not found';
  }

  Locale get currentLocale => _locale;

  String get currentLanguage => _locale.languageCode;

  static Future<I18n> load(Locale locale) async {
    final translations = I18n(locale);
    _localizedValues = _allValues[locale.toString()];
    return translations;
  }
}

class I18nDelegate extends LocalizationsDelegate<I18n> {
  const I18nDelegate();

  static final Set<Locale> supportedLocals = {
    Locale('en'),
    Locale('id'),
    Locale('zh'),
  };

  @override
  bool isSupported(Locale locale) => supportedLocals.contains(locale);

  @override
  Future<I18n> load(Locale locale) => I18n.load(locale);

  @override
  bool shouldReload(I18nDelegate old) => false;
}
